apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rxy1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpjk-tenant/rhtap-demo-app/hacbs-test-project-rxy1@sha256:1d8bc901830de11e56bb843e88aa7b8f35cebeaf23d3a97d9249976cd2c5b6a2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
