apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rxy1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpjk-tenant/rhtap-demo-app/hacbs-test-project-rxy1@sha256:1bc9781ec33e38ade9d9612dfd2dd9e16fcd63a000375b6b005d464464de5d6d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
