apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rxy1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rxy1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rxy1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rxy1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rxy1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpjk-tenant/rhtap-demo-app/hacbs-test-project-rxy1@sha256:1d8bc901830de11e56bb843e88aa7b8f35cebeaf23d3a97d9249976cd2c5b6a2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
